# Generated by Django 5.2.9 on 2025-12-19 20:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_text', models.CharField(blank=True, default='', max_length=255)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('severity', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('REPORTED', 'Signalé'), ('DIAGNOSED', 'Diagnostiqué'), ('WAITING_PARTS', 'En attente pièces'), ('PLANNED', 'Planifié'), ('IN_REPAIR', 'En réparation'), ('TESTING', 'En test'), ('RETURNED_TO_SERVICE', 'Remis en service'), ('CLOSED', 'Fermé'), ('BLOCKED', 'Bloqué'), ('CANCELLED', 'Annulé')], default='REPORTED', max_length=24)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needed_by_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Fermée')], default='OPEN', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='logistics.correctiveticket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('TO_ORDER', 'À commander'), ('ORDERED', 'Commandée'), ('SHIPPED', 'Expédiée'), ('RECEIVED', 'Reçue'), ('CONSUMED', 'Consommée'), ('RETURNED', 'Retournée')], default='TO_ORDER', max_length=16)),
                ('vendor', models.CharField(blank=True, default='', max_length=255)),
                ('order_number', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ordered_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('part_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.partrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(max_length=24)),
                ('new_status', models.CharField(max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='logistics.correctiveticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
