# Generated by Django 5.2.17 on 2026-08-16 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_correctiveticket_planned_for"),
        ("org", "0002_dynamicfielddefinition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(max_length=255, verbose_name="Référence"),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=0, verbose_name="Quantité"),
                ),
                (
                    "quantite_minimale",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantité minimale"
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Emplacement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_pieces",
                        to="org.section",
                        verbose_name="Section",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_pieces",
                        to="org.sector",
                        verbose_name="Secteur",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_pieces",
                        to="org.service",
                        verbose_name="Service",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_pieces",
                        to="org.ship",
                        verbose_name="Navire",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce en stock",
                "verbose_name_plural": "Pièces en stock",
                "ordering": ["reference"],
            },
        ),
    ]
