# Generated by Django 5.2.17 on 2026-08-18 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_stockpiece"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correctiveticket",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_tickets", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
