# Generated by Django 5.2.17 on 2026-08-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_correctiveticket_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="correctiveticket",
            name="diagnostic_final",
            field=models.TextField(
                blank=True, default="", verbose_name="Diagnostic final"
            ),
        ),
        migrations.AddField(
            model_name="correctiveticket",
            name="solution",
            field=models.TextField(
                blank=True, default="", verbose_name="Solution appliquée"
            ),
        ),
    ]
