# Generated by Django 5.2.17 on 2026-08-20 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_correctiveticket_diagnostic_final_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correctiveticket",
            name="date_validation",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de validation"
            ),
        ),
        migrations.AddField(
            model_name="correctiveticket",
            name="valide_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_valides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validé par",
            ),
        ),
    ]
