# Generated by Django 5.2.7 on 2026-08-26 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_correctiveticket_date_validation_and_more'),
        ('org', '0004_alter_ship_options_ship_type_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpiece',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_pieces', to='org.ship', verbose_name='Unité'),
        ),
    ]
