# Generated by Django 5.2.17 on 2026-08-28 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_merge_20260820_1444'),
        ('logistics', '0007_alter_stockpiece_ship_verbose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpiece',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_stock', to='assets.asset', verbose_name='Matériel lié'),
        ),
        migrations.AddField(
            model_name='stockpiece',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_stock', to='assets.installation', verbose_name='Installation liée'),
        ),
        migrations.AddField(
            model_name='stockpiece',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='stockpiece',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='stock_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='stockpiece',
            name='quantite_critique',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seuil critique'),
        ),
    ]
