# Generated by Django 5.2.17 on 2026-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_stockpiece_asset_stockpiece_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpiece',
            name='nno',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='NNO (Numéro de Nomenclature OTAN)'),
        ),
    ]
