# Generated by Django 5.2.7 on 2026-09-21 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_migrer_zones_vers_positions'),
        ('logistics', '0009_stockpiece_nno'),
        ('org', '0007_responsableclassenavire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('gravite', models.PositiveSmallIntegerField(default=3, verbose_name='Gravité')),
                ('statut', models.CharField(choices=[('SIGNALEE', 'Signalée'), ('PRISE_EN_COMPTE', 'Prise en compte'), ('TRAITEE', 'Traitée'), ('CLOTUREE', 'Clôturée')], default='SIGNALEE', max_length=20, verbose_name='Statut')),
                ('localisation', models.CharField(blank=True, default='', max_length=255, verbose_name='Localisation')),
                ('photo', models.FileField(blank=True, null=True, upload_to='anomalie_photos/', verbose_name='Photo')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='assets.asset', verbose_name='Matériel concerné')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='assets.installation', verbose_name='Installation concernée')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='org.section')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='org.sector')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='org.service')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='org.ship')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalie_source', to='logistics.correctiveticket', verbose_name="Ticket correctif issu de l'anomalie")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalieStatutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='logistics.anomalie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
