# Generated by Django 5.2.7 on 2026-09-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_migrer_zones_vers_positions'),
        ('logistics', '0010_anomalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveticket',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='assets.installation', verbose_name='Installation concernée'),
        ),
        migrations.AlterField(
            model_name='correctiveticket',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='assets.asset'),
        ),
    ]
