# Generated by Django 5.2.17 on 2026-09-23 22:17

import matrix.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_ticket_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='anomalie_photos/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='stockpiece',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='stock_photos/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)], verbose_name='Photo'),
        ),
    ]
