# Generated by Django 5.2.17 on 2026-10-10 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Consigne"),
                ),
                ("echeance", models.DateField(verbose_name="Échéance")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("A_FAIRE", "À faire"),
                            ("EN_COURS", "En cours"),
                            ("BLOQUEE", "Bloquée"),
                            ("TERMINEE", "Terminée"),
                        ],
                        default="A_FAIRE",
                        max_length=16,
                    ),
                ),
                (
                    "motif_blocage",
                    models.TextField(
                        blank=True, default="", verbose_name="Motif du blocage"
                    ),
                ),
                (
                    "compte_rendu",
                    models.TextField(
                        blank=True, default="", verbose_name="Compte rendu"
                    ),
                ),
                ("terminee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "assigne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches_assignees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assignée à",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="taches_suivies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Interlocuteurs du fil",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
                "ordering": ("echeance", "pk"),
            },
        ),
    ]
