# Generated by Django 5.2.17 on 2026-10-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametresTaches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jours_entre_relances",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="Jours entre deux relances (0 : pas de relance)",
                    ),
                ),
                (
                    "relancer_assigne",
                    models.BooleanField(
                        default=True, verbose_name="Relancer le marin assigné"
                    ),
                ),
                (
                    "relancer_chef_attributeur",
                    models.BooleanField(
                        default=True,
                        verbose_name="Relancer le chef qui a attribué la tâche",
                    ),
                ),
                (
                    "relancer_chefs_si_blocage",
                    models.BooleanField(
                        default=True,
                        verbose_name="Relancer les chefs du périmètre pour un blocage en retard",
                    ),
                ),
                (
                    "jours_terminees_affichees",
                    models.PositiveSmallIntegerField(
                        default=30,
                        verbose_name="Jours d'affichage des tâches terminées dans la vue d'avancement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglages des tâches",
                "verbose_name_plural": "Réglages des tâches",
            },
        ),
    ]
