# Generated by Django 5.2.17 on 2026-10-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taches", "0002_parametres_taches"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="partagee",
            field=models.BooleanField(
                default=True,
                help_text="Une tâche personnelle reste privée tant que le marin ne la partage pas.",
                verbose_name="Visible des chefs",
            ),
        ),
        migrations.AddField(
            model_name="tache",
            name="priorite",
            field=models.CharField(
                choices=[("NORMALE", "Normale"), ("URGENTE", "Urgente")],
                default="NORMALE",
                max_length=8,
                verbose_name="Priorité",
            ),
        ),
    ]
