# Generated by Django 5.2.17 on 2026-10-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taches", "0003_priorite_et_partage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tache",
            options={
                "ordering": (
                    models.OrderBy(models.F("echeance"), nulls_last=True),
                    "pk",
                ),
                "verbose_name": "Tâche",
                "verbose_name_plural": "Tâches",
            },
        ),
        migrations.AlterField(
            model_name="tache",
            name="echeance",
            field=models.DateField(blank=True, null=True, verbose_name="Échéance"),
        ),
    ]
