# Generated by Django 5.2.17 on 2026-09-23 22:17

import matrix.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='thread_attachments/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'odt', 'ods', 'txt', 'csv'), 20971520, verifier_image=True)]),
        ),
    ]
