# Generated by Django 5.2.9 on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_designation_asset_gisement_asset_marque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='photo',
            field=models.FileField(upload_to='asset_photos/', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='photo',
            field=models.FileField(upload_to='installation_photos/', null=True, blank=True),
        ),
    ]
