# Generated by Django 5.2.9 on 2025-12-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetfolder_asset_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='nno',
        ),
    ]
