# Generated by Django 5.2.9 on 2025-12-22
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_installation_nno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetfolder',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assetfolder_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetfolder',
            name='updated_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_assetfolder_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='local',
            field=models.CharField(max_length=255, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='installation',
            name='local',
            field=models.CharField(max_length=255, blank=True, default=''),
        ),
    ]
