# Generated by Django 5.2.9 on 2025-12-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_assetfolder_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationBigrameChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='assetfolder',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='folder_photos/'),
        ),
        migrations.AddField(
            model_name='installation',
            name='bigrame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='assets.installationbigramechoice'),
        ),
    ]
