# Generated by Django 5.2.9 on 2025-12-22 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_installationevent_installationeventattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationpart',
            name='nno',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='installationpart',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='installation_parts/'),
        ),
        migrations.AlterField(
            model_name='installationevent',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
