# Generated by Django 5.2.9 on 2025-12-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_installationhourreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationhourreading',
            name='is_visit',
            field=models.BooleanField(default=False),
        ),
    ]
