# Generated by Django 5.2.9 on 2025-12-22
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_installationhourreading_visit_flag'),
        ('assets', '0012_installationvibrationreading'),
    ]

    operations = []
