# Generated by Django 5.2.9 on 2025-12-22
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_merge_20251222_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='vib_days_a',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='installation',
            name='vib_days_b',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='installation',
            name='vib_days_c',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
