# Generated by Django 5.2.9 on 2025-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_installationisolationreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='iso_periodicity',
            field=models.CharField(choices=[('M', 'Mensuel'), ('T', 'Trimestriel'), ('A', 'Annuel')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='installationisolationreading',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
