# Generated by Django 5.2.17 on 2026-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0020_alter_installationextrafield_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installationmaintenance",
            name="derniere_echeance_heures",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="intervalle",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="mode_declenchement",
            field=models.CharField(
                choices=[
                    ("CALENDRIER", "Calendaire"),
                    ("COMPTEUR", "Compteur (heures de marche)"),
                    ("LES_DEUX", "Le premier des deux"),
                ],
                default="CALENDRIER",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="seuil_heures",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="unite_intervalle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("J", "Jour(s)"),
                    ("S", "Semaine(s)"),
                    ("M", "Mois"),
                    ("A", "Année(s)"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
