# Generated by Django 5.2.17 on 2026-08-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0021_installationmaintenance_derniere_echeance_heures_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sous_ensembles",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sous_ensembles",
                to="assets.installation",
            ),
        ),
    ]
