# Generated by Django 5.2.17 on 2026-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0022_asset_parent_installation_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="critique",
            field=models.BooleanField(
                default=False, verbose_name="Installation critique"
            ),
        ),
    ]
