# Generated by Django 5.2.17 on 2026-08-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0023_installation_critique"),
        ("assets", "0023_installation_isolation_seuil_ohms"),
    ]

    operations = []
