# Generated by Django 5.2.17 on 2026-08-28 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_merge_20260820_1444'),
        ('org', '0005_ship_classe_navire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du pont')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='org.ship', verbose_name='Navire')),
            ],
            options={
                'verbose_name': 'Pont',
                'verbose_name_plural': 'Ponts',
                'ordering': ['ship__name', 'order', 'name'],
                'unique_together': {('ship', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la zone')),
                ('points', models.JSONField(blank=True, default=list, help_text="Liste de points {x, y} en pourcentage (0-100) de l'image du pont.", verbose_name='Contour de la zone')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='assets.deck', verbose_name='Pont')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='assets.location', verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['deck__ship__name', 'deck__order', 'deck__name', 'name'],
            },
        ),
    ]
