# Generated by Django 5.2.7 on 2026-08-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_deck_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='deck_images/', verbose_name='Image du plan'),
        ),
    ]
