# Generated by Django 5.2.7 on 2026-09-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_deck_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='plan_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_positionnes', to='assets.deck', verbose_name='Pont du plan'),
        ),
        migrations.AddField(
            model_name='asset',
            name='position_x',
            field=models.FloatField(blank=True, null=True, verbose_name='Position X (%)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='position_y',
            field=models.FloatField(blank=True, null=True, verbose_name='Position Y (%)'),
        ),
    ]
