# Generated by Django 5.2.17 on 2026-09-23 22:17

import matrix.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_migrer_zones_vers_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='asset_photos/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)]),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='file',
            field=models.FileField(upload_to='asset_docs/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'odt', 'ods', 'txt', 'csv'), 20971520, verifier_image=True)]),
        ),
        migrations.AlterField(
            model_name='assetfolder',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='folder_photos/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='deck_images/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)], verbose_name='Image du plan'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='installation_photos/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)]),
        ),
        migrations.AlterField(
            model_name='installationeventattachment',
            name='file',
            field=models.FileField(upload_to='installation_events/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'odt', 'ods', 'txt', 'csv'), 20971520, verifier_image=True)]),
        ),
        migrations.AlterField(
            model_name='installationmaintenanceattachment',
            name='file',
            field=models.FileField(upload_to='installation_maintenance/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'odt', 'ods', 'txt', 'csv'), 20971520, verifier_image=True)]),
        ),
        migrations.AlterField(
            model_name='installationpart',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='installation_parts/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'), 10485760, verifier_image=True)]),
        ),
    ]
