# Generated by Django 5.2.17 on 2026-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0028_migrer_zones_vers_positions"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitemtemplate",
            name="valeur_max",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valeur maximale"
            ),
        ),
        migrations.AddField(
            model_name="checklistitemtemplate",
            name="valeur_min",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Valeur minimale"
            ),
        ),
    ]
