# Generated by Django 5.2.17 on 2026-10-07 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_userprofile_fonction_coma"),
        ("assets", "0029_checklistitemtemplate_valeur_max_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieCatalogue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Icône"
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="catalogue_categories/",
                        verbose_name="Photo",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enfants",
                        to="assets.categoriecatalogue",
                        verbose_name="Catégorie parente",
                    ),
                ),
                (
                    "specialite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories_catalogue",
                        to="accounts.specialitychoice",
                        verbose_name="Spécialité",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie du catalogue",
                "verbose_name_plural": "Catégories du catalogue",
                "ordering": ["specialite__name", "ordre", "nom"],
                "unique_together": {("parent", "nom")},
            },
        ),
        migrations.CreateModel(
            name="ArticleCatalogue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "marque",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Marque"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Modèle / référence",
                    ),
                ),
                (
                    "nno",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="NNO"
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="catalogue_articles/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "caracteristiques",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Caractéristiques"
                    ),
                ),
                (
                    "duree_vie_mois",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Durée de vie ou de péremption type (mois)",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articles",
                        to="assets.categoriecatalogue",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article du catalogue",
                "verbose_name_plural": "Articles du catalogue",
                "ordering": ["categorie__nom", "designation"],
            },
        ),
    ]
