# Generated by Django 5.2.17 on 2026-10-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0030_catalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="article_catalogue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exemplaires",
                to="assets.articlecatalogue",
                verbose_name="Article du catalogue",
            ),
        ),
    ]
