# Generated by Django 5.2.17 on 2026-10-07 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_userprofile_fonction_coma"),
        ("assets", "0031_asset_article_catalogue"),
        ("org", "0011_service_commandant_adjoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChefResponsableSpecialite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsables_specialite_diriges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chef du responsable",
                    ),
                ),
                (
                    "responsable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chef_designe",
                        to="accounts.responsablespecialite",
                        verbose_name="Responsable de spécialité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chef de responsable de spécialité",
                "verbose_name_plural": "Chefs de responsables de spécialité",
            },
        ),
        migrations.CreateModel(
            name="PropositionArticle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("visa_secteur", "Visa du chef de secteur"),
                            ("visa_service", "Visa du chef de service"),
                            ("visa_coma", "Visa du commandant adjoint"),
                            (
                                "verification",
                                "Vérification par le responsable de spécialité",
                            ),
                            (
                                "visa_chef_specialite",
                                "Visa du chef du responsable de spécialité",
                            ),
                            ("publiee", "Publiée au catalogue"),
                            ("refusee", "Renvoyée au rédacteur"),
                        ],
                        db_index=True,
                        default="visa_service",
                        max_length=24,
                    ),
                ),
                ("role_redacteur", models.CharField(max_length=32)),
                ("equipage", models.CharField(blank=True, default="", max_length=8)),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "marque",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Marque"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Modèle / référence",
                    ),
                ),
                (
                    "nno",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="NNO"
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="catalogue_propositions/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "caracteristiques",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Caractéristiques"
                    ),
                ),
                (
                    "duree_vie_mois",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Durée de vie ou de péremption type (mois)",
                    ),
                ),
                ("motif_refus", models.TextField(blank=True, default="")),
                (
                    "article",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposition",
                        to="assets.articlecatalogue",
                        verbose_name="Article publié",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="propositions",
                        to="assets.categoriecatalogue",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propositions_article",
                        to="org.sector",
                        verbose_name="Secteur du rédacteur",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions_article",
                        to="org.service",
                        verbose_name="Service d'origine",
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions_article",
                        to="org.ship",
                        verbose_name="Bâtiment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verificateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propositions_article_verifiees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposition d'article",
                "verbose_name_plural": "Propositions d'article",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvenementProposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("soumise", "Soumise"),
                            ("resoumise", "Soumise à nouveau"),
                            ("visee", "Visée"),
                            ("corrigee", "Corrigée"),
                            ("verifiee", "Vérifiée"),
                            ("refusee", "Renvoyée au rédacteur"),
                            ("publiee", "Publiée"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "etape",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visa_secteur", "Visa du chef de secteur"),
                            ("visa_service", "Visa du chef de service"),
                            ("visa_coma", "Visa du commandant adjoint"),
                            (
                                "verification",
                                "Vérification par le responsable de spécialité",
                            ),
                            (
                                "visa_chef_specialite",
                                "Visa du chef du responsable de spécialité",
                            ),
                            ("publiee", "Publiée au catalogue"),
                            ("refusee", "Renvoyée au rédacteur"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("motif", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_proposition_article",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="assets.propositionarticle",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
