# Generated by Django 5.2.17 on 2026-10-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0032_propositions_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="date_dernier_controle",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date du dernier contrôle"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="date_mise_en_service",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de mise en service"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="date_peremption",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de péremption"
            ),
        ),
    ]
