# Generated by Django 5.2.17 on 2026-10-07 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0033_dates_materiel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentInstallation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("plan", "Plan"),
                            ("notice", "Notice"),
                            ("procedure", "Procédure"),
                            ("schema", "Schéma"),
                            ("certificat", "Certificat"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to="installation_docs/", verbose_name="Fichier"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="assets.installation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document d'installation",
                "verbose_name_plural": "Documents d'installation",
                "ordering": ["titre", "created_at"],
            },
        ),
    ]
