# Generated by Django 5.2.17 on 2026-10-07 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0034_document_installation"),
        ("logistics", "0011_ticket_installation"),
        ("org", "0011_service_commandant_adjoint"),
        ("training", "0014_alter_trainingrequirement_applies_to_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FicheEtape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("texte", models.TextField()),
                ("attention", models.TextField(blank=True, default="")),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FichePreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("outil", "Outil"),
                            ("piece", "Pièce ou consommable"),
                            ("epi", "Équipement de protection (EPI)"),
                            ("consigne", "Consigne de sécurité ou consignation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("ordre", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre", "pk"],
            },
        ),
        migrations.AddField(
            model_name="checklistitemtemplate",
            name="cle",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="description",
            field=models.TextField(
                blank=True, default="", verbose_name="Objet de la fiche"
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="duree_estimee_min",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Durée estimée (min)"
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="equipage",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="etat",
            field=models.CharField(
                choices=[
                    ("visa_secteur", "Visa du chef de secteur"),
                    ("visa_service", "Visa du chef de service"),
                    ("visa_coma", "Visa du commandant adjoint"),
                    ("validee", "Validée"),
                    ("refusee", "Renvoyée au rédacteur"),
                ],
                db_index=True,
                default="validee",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="fiche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="assets.installationmaintenance",
                verbose_name="Fiche",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="intervalle",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="mode_declenchement",
            field=models.CharField(
                choices=[
                    ("CALENDRIER", "Calendaire"),
                    ("COMPTEUR", "Compteur (heures de marche)"),
                    ("LES_DEUX", "Le premier des deux"),
                ],
                default="CALENDRIER",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="motif_refus",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="nb_personnes",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Nombre de personnes"
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="numero",
            field=models.PositiveIntegerField(default=1, verbose_name="Version"),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiches_maintenance",
                to="training.trainingcourse",
                verbose_name="Qualification requise",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="redacteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions_fiche_redigees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="resume_modifications",
            field=models.TextField(
                blank=True, default="", verbose_name="Ce qui change"
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="role_redacteur",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="seuil_heures",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="unite_intervalle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("J", "Jour(s)"),
                    ("S", "Semaine(s)"),
                    ("M", "Mois"),
                    ("A", "Année(s)"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="valide_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evenementproposition",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements",
                to="assets.checklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiches_maintenance",
                to="assets.categoriecatalogue",
                verbose_name="Catégorie de matériel",
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="niveau",
            field=models.CharField(
                choices=[("BORD", "Fiche du bord"), ("FLOTTE", "Fiche flotte")],
                default="BORD",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="evenementproposition",
            name="proposition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements",
                to="assets.propositionarticle",
            ),
        ),
        migrations.AlterField(
            model_name="installationmaintenance",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenances",
                to="assets.installation",
            ),
        ),
        migrations.AddConstraint(
            model_name="checklisttemplate",
            constraint=models.UniqueConstraint(
                fields=("fiche", "numero"), name="version_fiche_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="evenementproposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("proposition__isnull", False), ("version__isnull", True)),
                    models.Q(("proposition__isnull", True), ("version__isnull", False)),
                    _connector="OR",
                ),
                name="evenement_proposition_xor_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="installationmaintenance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("categorie__isnull", True), ("installation__isnull", False)
                    ),
                    models.Q(
                        ("categorie__isnull", False), ("installation__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="fiche_installation_xor_categorie",
            ),
        ),
        migrations.AddField(
            model_name="ficheetape",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="etapes",
                to="assets.checklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="fichepreparation",
            name="piece",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fiches_maintenance",
                to="logistics.stockpiece",
                verbose_name="Pièce du stock",
            ),
        ),
        migrations.AddField(
            model_name="fichepreparation",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preparations",
                to="assets.checklisttemplate",
            ),
        ),
    ]
