# Generated by Django 5.2.17 on 2026-10-08 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_userprofile_fonction_coma"),
        ("assets", "0036_fiches_version_1"),
        ("org", "0011_service_commandant_adjoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignalementFiche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("texte", models.TextField(verbose_name="Ce qui est faux ou manque")),
                ("traite", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="secteur_origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="org.sector",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="service_origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="org.service",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="ship_origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="org.ship",
            ),
        ),
        migrations.AddField(
            model_name="checklisttemplate",
            name="verificateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions_fiche_verifiees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="classe_navire",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Classe de navire visée",
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="equipement",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Installation visée (désignation)",
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="origine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adaptations",
                to="assets.installationmaintenance",
                verbose_name="Fiche flotte d'origine",
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="origine_en_attente",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="origine_numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="reference_equipement",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Référence de l'installation visée",
            ),
        ),
        migrations.AddField(
            model_name="installationmaintenance",
            name="specialite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiches_maintenance",
                to="accounts.specialitychoice",
                verbose_name="Spécialité",
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="etat",
            field=models.CharField(
                choices=[
                    ("visa_secteur", "Visa du chef de secteur"),
                    ("visa_service", "Visa du chef de service"),
                    ("visa_coma", "Visa du commandant adjoint"),
                    ("verification", "Vérification par le responsable de spécialité"),
                    (
                        "visa_chef_specialite",
                        "Visa du chef du responsable de spécialité",
                    ),
                    ("validee", "Validée"),
                    ("refusee", "Renvoyée au rédacteur"),
                ],
                db_index=True,
                default="validee",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_templates",
                to="org.sector",
            ),
        ),
        migrations.AddField(
            model_name="signalementfiche",
            name="auteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signalements_fiche",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="signalementfiche",
            name="fiche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signalements",
                to="assets.installationmaintenance",
            ),
        ),
        migrations.AddField(
            model_name="signalementfiche",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signalements",
                to="assets.checklisttemplate",
                verbose_name="Version signalée",
            ),
        ),
        migrations.AddField(
            model_name="signalementfiche",
            name="version_proposee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="assets.checklisttemplate",
            ),
        ),
    ]
