# Generated by Django 5.2.17 on 2026-10-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0039_fiches_cible_coherente"),
        ("maintenance", "0007_fiches_flotte"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitemtemplate",
            name="releve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("heures", "Heures de marche"),
                    ("isolement", "Isolement (Ω)"),
                    ("vibrations", "Vibrations (A, B ou C)"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="installationhourreading",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maintenance.maintenanceexecution",
                verbose_name="Compte rendu d'origine",
            ),
        ),
        migrations.AddField(
            model_name="installationisolationreading",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maintenance.maintenanceexecution",
                verbose_name="Compte rendu d'origine",
            ),
        ),
        migrations.AddField(
            model_name="installationvibrationreading",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="maintenance.maintenanceexecution",
                verbose_name="Compte rendu d'origine",
            ),
        ),
    ]
