# Generated by Django 5.2.17 on 2026-10-10 19:15

import matrix.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0040_validation_fichiers_televerses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecatalogue",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="catalogue_articles/",
                validators=[
                    matrix.core.validators.ValidateurFichierTeleverse(
                        ("jpg", "jpeg", "png", "webp"), 5242880, verifier_image=True
                    )
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="categoriecatalogue",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="catalogue_categories/",
                validators=[
                    matrix.core.validators.ValidateurFichierTeleverse(
                        ("jpg", "jpeg", "png", "webp"), 5242880, verifier_image=True
                    )
                ],
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="documentinstallation",
            name="fichier",
            field=models.FileField(
                upload_to="installation_docs/",
                validators=[
                    matrix.core.validators.ValidateurFichierTeleverse(
                        ("pdf", "png", "jpg", "jpeg", "webp", "txt", "docx", "xlsx"),
                        20971520,
                        verifier_image=True,
                    )
                ],
                verbose_name="Fichier",
            ),
        ),
        migrations.AlterField(
            model_name="propositionarticle",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="catalogue_propositions/",
                validators=[
                    matrix.core.validators.ValidateurFichierTeleverse(
                        ("jpg", "jpeg", "png", "webp"), 5242880, verifier_image=True
                    )
                ],
                verbose_name="Photo",
            ),
        ),
    ]
