# Generated by Django 5.2.17 on 2026-09-09 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0006_rolethresholdconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, default='', max_length=255)),
                ('date_debut', models.DateField(verbose_name='Début de période')),
                ('date_fin', models.DateField(verbose_name='Fin de période')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16)),
                ('publiee_le', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('duree_creneau_heures', models.PositiveSmallIntegerField(default=4, verbose_name="Durée par défaut d'un créneau (heures)")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_publiees', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.section')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.sector')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.service')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste de quarts',
                'verbose_name_plural': 'Listes de quarts',
                'ordering': ('-date_debut',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreneauQuart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.CharField(max_length=255, verbose_name='Poste')),
                ('debut', models.DateTimeField(verbose_name='Début')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('note', models.TextField(blank=True, default='')),
                ('marin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_affectes', to=settings.AUTH_USER_MODEL, verbose_name='Marin affecté')),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='quarts.quart')),
            ],
            options={
                'verbose_name': 'Créneau de quart',
                'verbose_name_plural': 'Créneaux de quart',
                'ordering': ('debut',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, default='', max_length=255)),
                ('date_debut', models.DateField(verbose_name='Début de période')),
                ('date_fin', models.DateField(verbose_name='Fin de période')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16)),
                ('publiee_le', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('type_service', models.CharField(blank=True, default='', max_length=255, verbose_name='Type de service')),
                ('duree_creneau_heures', models.PositiveSmallIntegerField(default=24, verbose_name="Durée par défaut d'un créneau (heures)")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_publiees', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.section')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.sector')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.service')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste de services de garde',
                'verbose_name_plural': 'Listes de services de garde',
                'ordering': ('-date_debut',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreneauServiceGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.CharField(max_length=255, verbose_name='Poste')),
                ('debut', models.DateTimeField(verbose_name='Début')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('note', models.TextField(blank=True, default='')),
                ('marin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_affectes', to=settings.AUTH_USER_MODEL, verbose_name='Marin affecté')),
                ('service_garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='quarts.servicegarde')),
            ],
            options={
                'verbose_name': 'Créneau de service de garde',
                'verbose_name_plural': 'Créneaux de service de garde',
                'ordering': ('debut',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChefDeListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefs_de_liste', to='org.section')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefs_de_liste', to='org.sector')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefs_de_liste', to='org.service')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chefs_de_liste', to='org.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations_chef_de_liste', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef de liste',
                'verbose_name_plural': 'Chefs de liste',
                'unique_together': {('user', 'ship', 'service', 'sector', 'section')},
            },
        ),
    ]
