# Generated by Django 5.2.17 on 2026-09-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fonctionquartchoice'),
        ('quarts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quart',
            name='fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quarts', to='accounts.fonctionquartchoice', verbose_name='Fonction de quart'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='fonction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services_garde', to='accounts.servicefunctionchoice', verbose_name='Fonction de service'),
        ),
    ]
