# Generated by Django 5.2.7 on 2026-09-21 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarts', '0002_quart_fonction_servicegarde_fonction'),
        ('training', '0013_trainingcourse_bareme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegarde',
            name='delai_minimal_echange_heures',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Délai minimal avant le tour pour demander un échange (heures)'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='formations_requises',
            field=models.ManyToManyField(blank=True, related_name='services_garde_exigeant', to='training.trainingcourse', verbose_name='Habilitations requises pour tenir ce service'),
        ),
        migrations.CreateModel(
            name='EchangeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle_creneau_demandeur', models.CharField(default='', max_length=255)),
                ('libelle_creneau_cible', models.CharField(default='', max_length=255)),
                ('statut', models.CharField(choices=[('DEMANDE', "En attente de l'accord du marin"), ('ACCEPTE', 'En attente du chef de liste'), ('VALIDE', 'Échange validé'), ('REFUSE', 'Refusé par le marin'), ('REJETE', 'Refusé par le chef de liste'), ('ANNULE', 'Annulé')], default='DEMANDE', max_length=16)),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif de la demande')),
                ('motif_decision', models.TextField(blank=True, default='', verbose_name='Motif du refus')),
                ('accepte_le', models.DateTimeField(blank=True, null=True)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('cible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_proposes_a', to=settings.AUTH_USER_MODEL)),
                ('creneau_cible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_recus', to='quarts.creneauservicegarde')),
                ('creneau_demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_proposes', to='quarts.creneauservicegarde')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_decides', to=settings.AUTH_USER_MODEL)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Échange de service',
                'verbose_name_plural': 'Échanges de service',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EchangeServiceEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('echange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='quarts.echangeservice')),
            ],
            options={
                'verbose_name': "Événement d'échange",
                'verbose_name_plural': "Événements d'échange",
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
