# Generated by Django 5.2.17 on 2026-10-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_service_commandant_adjoint'),
        ('quarts', '0003_echange_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quart',
            name='equipage',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Équipage'),
        ),
        migrations.AddField(
            model_name='quart',
            name='proposee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposée le'),
        ),
        migrations.AddField(
            model_name='quart',
            name='proposee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_proposees', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='equipage',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Équipage'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='proposee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposée le'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='proposee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_proposees', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par'),
        ),
        migrations.AlterField(
            model_name='quart',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROPOSEE', 'Proposée'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16),
        ),
        migrations.AlterField(
            model_name='servicegarde',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROPOSEE', 'Proposée'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16),
        ),
        migrations.CreateModel(
            name='FeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipage', models.CharField(blank=True, default='', help_text='Renseigné uniquement sur un bâtiment à double équipage.', max_length=8, verbose_name='Équipage')),
                ('date', models.DateField(verbose_name='Date concernée')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VISA_SECTEUR', 'En attente du visa du chef de secteur'), ('VISA_SERVICE', 'En attente du visa du chef de service'), ('VISA_COMAEQ', 'En attente du visa du COMAEQ'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16)),
                ('valeurs_entete', models.JSONField(blank=True, default=dict, help_text='Dictionnaire {id de la rubrique : valeur saisie} pour les rubriques « saisie chaque jour ».', verbose_name="Valeurs des rubriques d'en-tête")),
                ('proposee_le', models.DateTimeField(blank=True, null=True, verbose_name='Proposée le')),
                ('visa_secteur_le', models.DateTimeField(blank=True, null=True, verbose_name='Visa secteur le')),
                ('visa_service_le', models.DateTimeField(blank=True, null=True, verbose_name='Visa service le')),
                ('visa_comaeq_le', models.DateTimeField(blank=True, null=True, verbose_name='Visa COMAEQ le')),
                ('publiee_le', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('motif_retour', models.TextField(blank=True, default='', verbose_name='Motif du dernier renvoi en brouillon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('proposee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('secteur_redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.sector', verbose_name='Secteur du rédacteur')),
                ('service_redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.service', verbose_name='Service du rédacteur')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_service', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('visa_comaeq_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Visa COMAEQ par')),
                ('visa_secteur_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Visa secteur par')),
                ('visa_service_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Visa service par')),
            ],
            options={
                'verbose_name': 'Feuille de service',
                'verbose_name_plural': 'Feuilles de service',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FonctionFeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Fonction')),
                ('poste_recherche', models.CharField(blank=True, default='', help_text='Doit correspondre exactement au champ « Poste » saisi sur le créneau de service de garde (insensible à la casse). Laisser vide si identique au libellé ci-dessus.', max_length=255, verbose_name='Poste correspondant dans les tours de service')),
                ('actif', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions_feuille_service', to='org.ship')),
            ],
            options={
                'verbose_name': 'Fonction de service (feuille de service)',
                'verbose_name_plural': 'Fonctions de service (feuille de service)',
                'ordering': ('ordre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RubriqueEnTeteFeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Libellé')),
                ('type_saisie', models.CharField(choices=[('FIXE', 'Fixe (valeur du navire)'), ('QUOTIDIENNE', 'Saisie chaque jour')], default='QUOTIDIENNE', max_length=16)),
                ('valeur_fixe', models.CharField(blank=True, default='', max_length=255, verbose_name='Valeur (rubrique fixe)')),
                ('actif', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques_feuille_service', to='org.ship')),
            ],
            options={
                'verbose_name': "Rubrique d'en-tête (feuille de service)",
                'verbose_name_plural': "Rubriques d'en-tête (feuille de service)",
                'ordering': ('ordre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Scénario')),
                ('famille', models.CharField(choices=[('SECURITE', "Sécurité (incendie, voie d'eau, sinistre)"), ('PROTECTION', 'Protection-défense (menace extérieure ou malveillante)')], default='SECURITE', max_length=16)),
                ('adjoint_sigle', models.CharField(blank=True, default='', help_text='Vide : COMANAV pour la sécurité, COMAEQ pour la protection-défense.', max_length=10, verbose_name='COMA responsable')),
                ('actif', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_alerte', to='org.ship')),
            ],
            options={
                'verbose_name': "Scénario d'alerte",
                'verbose_name_plural': "Scénarios d'alerte",
                'ordering': ('ordre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PosteAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Rôle à tenir')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Poste obligatoire')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quarts.fonctionfeuilleservice', verbose_name='Fonction de service')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='quarts.scenarioalerte')),
            ],
            options={
                'verbose_name': "Poste d'un scénario d'alerte",
                'verbose_name_plural': "Postes des scénarios d'alerte",
                'ordering': ('ordre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ModificationOrganisationAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREER', 'Création'), ('MODIFIER', 'Modification'), ('SUPPRIMER', 'Suppression')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=12)),
                ('donnees', models.JSONField(blank=True, default=dict, help_text='Définition proposée du scénario : libellé, famille, COMA, ordre, état et postes.')),
                ('decidee_le', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('decidee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décidée par')),
                ('proposee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications_alerte', to='org.ship')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='quarts.scenarioalerte')),
            ],
            options={
                'verbose_name': "Modification de l'organisation d'alerte",
                'verbose_name_plural': "Modifications de l'organisation d'alerte",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VersionFeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('publiee_le', models.DateTimeField(verbose_name='Publiée le')),
                ('contenu_fige', models.JSONField(default=dict, verbose_name='Contenu figé (en-tête + personnel)')),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quarts.feuilleservice')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
            ],
            options={
                'verbose_name': 'Version de feuille de service',
                'verbose_name_plural': 'Versions de feuille de service',
                'ordering': ('-numero',),
            },
        ),
        migrations.CreateModel(
            name='VersionQuart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('publiee_le', models.DateTimeField(verbose_name='Publiée le')),
                ('creneaux_fige', models.JSONField(default=list, verbose_name='Créneaux figés')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quarts.quart')),
            ],
            options={
                'verbose_name': 'Version de liste de quarts',
                'verbose_name_plural': 'Versions de liste de quarts',
                'ordering': ('-numero',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VersionServiceGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('publiee_le', models.DateTimeField(verbose_name='Publiée le')),
                ('creneaux_fige', models.JSONField(default=list, verbose_name='Créneaux figés')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('service_garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quarts.servicegarde')),
            ],
            options={
                'verbose_name': 'Version de liste de services de garde',
                'verbose_name_plural': 'Versions de liste de services de garde',
                'ordering': ('-numero',),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='feuilleservice',
            constraint=models.UniqueConstraint(fields=('ship', 'equipage', 'date'), name='feuille_service_unique_equipage_date'),
        ),
        migrations.AlterUniqueTogether(
            name='fonctionfeuilleservice',
            unique_together={('ship', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='rubriqueentetefeuilleservice',
            unique_together={('ship', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='scenarioalerte',
            unique_together={('ship', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='versionfeuilleservice',
            unique_together={('feuille', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='versionquart',
            unique_together={('quart', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='versionservicegarde',
            unique_together={('service_garde', 'numero')},
        ),
    ]
