# Generated by Django 5.2.17 on 2026-09-22 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarts', '0003_echange_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quart',
            name='proposee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposée le'),
        ),
        migrations.AddField(
            model_name='quart',
            name='proposee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_proposees', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='proposee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Proposée le'),
        ),
        migrations.AddField(
            model_name='servicegarde',
            name='proposee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_proposees', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par'),
        ),
        migrations.AlterField(
            model_name='quart',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROPOSEE', 'Proposée'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16),
        ),
        migrations.AlterField(
            model_name='servicegarde',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PROPOSEE', 'Proposée'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16),
        ),
        migrations.CreateModel(
            name='VersionQuart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('publiee_le', models.DateTimeField(verbose_name='Publiée le')),
                ('creneaux_fige', models.JSONField(default=list, verbose_name='Créneaux figés')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quarts.quart')),
            ],
            options={
                'verbose_name': 'Version de liste de quarts',
                'verbose_name_plural': 'Versions de liste de quarts',
                'ordering': ('-numero',),
                'abstract': False,
                'unique_together': {('quart', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='VersionServiceGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('publiee_le', models.DateTimeField(verbose_name='Publiée le')),
                ('creneaux_fige', models.JSONField(default=list, verbose_name='Créneaux figés')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('service_garde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quarts.servicegarde')),
            ],
            options={
                'verbose_name': 'Version de liste de services de garde',
                'verbose_name_plural': 'Versions de liste de services de garde',
                'ordering': ('-numero',),
                'abstract': False,
                'unique_together': {('service_garde', 'numero')},
            },
        ),
    ]
