# Generated by Django 5.2.7 on 2026-09-24 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_moduleactivation'),
        ('quarts', '0004_quart_proposee_le_quart_proposee_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date concernée')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VISA_SECTEUR', 'En attente du visa du chef de secteur'), ('VISA_SERVICE', 'En attente du visa du chef de service'), ('VISA_COMAEQ', 'En attente du visa du COMAEQ'), ('PUBLIEE', 'Publiée')], default='BROUILLON', max_length=16)),
                ('valeurs_entete', models.JSONField(blank=True, default=dict, help_text='Dictionnaire {id de la rubrique : valeur saisie} pour les rubriques « saisie chaque jour ».', verbose_name="Valeurs des rubriques d'en-tête")),
                ('proposee_le', models.DateTimeField(blank=True, null=True, verbose_name='Proposée le')),
                ('visa_secteur_le', models.DateTimeField(blank=True, null=True, verbose_name='Visa secteur le')),
                ('visa_service_le', models.DateTimeField(blank=True, null=True, verbose_name='Visa service le')),
                ('visa_comaeq_le', models.DateTimeField(blank=True, null=True, verbose_name='Visa COMAEQ le')),
                ('publiee_le', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('motif_retour', models.TextField(blank=True, default='', verbose_name='Motif du dernier renvoi en brouillon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('proposee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
                ('secteur_redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.sector', verbose_name='Secteur du rédacteur')),
                ('service_redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.service', verbose_name='Service du rédacteur')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_service', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('visa_comaeq_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Visa COMAEQ par')),
                ('visa_secteur_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Visa secteur par')),
                ('visa_service_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Visa service par')),
            ],
            options={
                'verbose_name': 'Feuille de service',
                'verbose_name_plural': 'Feuilles de service',
                'ordering': ('-date',),
                'unique_together': {('ship', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FonctionFeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Fonction')),
                ('poste_recherche', models.CharField(blank=True, default='', help_text='Doit correspondre exactement au champ « Poste » saisi sur le créneau de service de garde (insensible à la casse). Laisser vide si identique au libellé ci-dessus.', max_length=255, verbose_name='Poste correspondant dans les tours de service')),
                ('actif', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctions_feuille_service', to='org.ship')),
            ],
            options={
                'verbose_name': 'Fonction de service (feuille de service)',
                'verbose_name_plural': 'Fonctions de service (feuille de service)',
                'ordering': ('ordre', 'pk'),
                'unique_together': {('ship', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='RubriqueEnTeteFeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Libellé')),
                ('type_saisie', models.CharField(choices=[('FIXE', 'Fixe (valeur du navire)'), ('QUOTIDIENNE', 'Saisie chaque jour')], default='QUOTIDIENNE', max_length=16)),
                ('valeur_fixe', models.CharField(blank=True, default='', max_length=255, verbose_name='Valeur (rubrique fixe)')),
                ('actif', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques_feuille_service', to='org.ship')),
            ],
            options={
                'verbose_name': "Rubrique d'en-tête (feuille de service)",
                'verbose_name_plural': "Rubriques d'en-tête (feuille de service)",
                'ordering': ('ordre', 'pk'),
                'unique_together': {('ship', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='VersionFeuilleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('publiee_le', models.DateTimeField(verbose_name='Publiée le')),
                ('contenu_fige', models.JSONField(default=dict, verbose_name='Contenu figé (en-tête + personnel)')),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='quarts.feuilleservice')),
                ('publiee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
            ],
            options={
                'verbose_name': 'Version de feuille de service',
                'verbose_name_plural': 'Versions de feuille de service',
                'ordering': ('-numero',),
                'unique_together': {('feuille', 'numero')},
            },
        ),
    ]
