# Generated by Django 5.2.7 on 2026-09-30 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rattacher_feuilles_existantes(apps, schema_editor):
    """Les feuilles déjà rédigées sur un bâtiment à double équipage étaient
    celles de l'équipage à bord : on les lui rattache (rien n'est perdu)."""
    FeuilleService = apps.get_model("quarts", "FeuilleService")
    for feuille in FeuilleService.objects.filter(ship__double_equipage=True, ship__equipage_a_bord__isnull=False):
        feuille.equipage_id = feuille.ship.equipage_a_bord_id
        feuille.save(update_fields=["equipage"])


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_synthese_passation'),
        ('quarts', '0005_feuilleservice_fonctionfeuilleservice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feuilleservice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feuilleservice',
            name='equipage',
            field=models.ForeignKey(blank=True, help_text='Renseigné uniquement sur un bâtiment à double équipage.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_service', to='org.equipage', verbose_name='Équipage'),
        ),
        migrations.RunPython(rattacher_feuilles_existantes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='feuilleservice',
            constraint=models.UniqueConstraint(condition=models.Q(('equipage__isnull', True)), fields=('ship', 'date'), name='feuille_service_unique_navire_date'),
        ),
        migrations.AddConstraint(
            model_name='feuilleservice',
            constraint=models.UniqueConstraint(condition=models.Q(('equipage__isnull', False)), fields=('ship', 'equipage', 'date'), name='feuille_service_unique_equipage_date'),
        ),
    ]
