# Generated by Django 5.2.17 on 2026-10-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_rolethresholdconfig_droits_en_second_and_more'),
        ('quarts', '0006_feuille_service_par_equipage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Scénario')),
                ('famille', models.CharField(choices=[('SECURITE', "Sécurité (incendie, voie d'eau, sinistre)"), ('PROTECTION', 'Protection-défense (menace extérieure ou malveillante)')], default='SECURITE', max_length=16)),
                ('adjoint_sigle', models.CharField(blank=True, default='', help_text='Vide : COMANAV pour la sécurité, COMAEQ pour la protection-défense.', max_length=10, verbose_name='COMA responsable')),
                ('actif', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_alerte', to='org.ship')),
            ],
            options={
                'verbose_name': "Scénario d'alerte",
                'verbose_name_plural': "Scénarios d'alerte",
                'ordering': ('ordre', 'pk'),
                'unique_together': {('ship', 'libelle')},
            },
        ),
        migrations.CreateModel(
            name='PosteAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=128, verbose_name='Rôle à tenir')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Poste obligatoire')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quarts.fonctionfeuilleservice', verbose_name='Fonction de service')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='quarts.scenarioalerte')),
            ],
            options={
                'verbose_name': "Poste d'un scénario d'alerte",
                'verbose_name_plural': "Postes des scénarios d'alerte",
                'ordering': ('ordre', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ModificationOrganisationAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREER', 'Création'), ('MODIFIER', 'Modification'), ('SUPPRIMER', 'Suppression')], max_length=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=12)),
                ('donnees', models.JSONField(blank=True, default=dict, help_text='Définition proposée du scénario : libellé, famille, COMA, ordre, état et postes.')),
                ('decidee_le', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('decidee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décidée par')),
                ('proposee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Proposée par')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications_alerte', to='org.ship')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='quarts.scenarioalerte')),
            ],
            options={
                'verbose_name': "Modification de l'organisation d'alerte",
                'verbose_name_plural': "Modifications de l'organisation d'alerte",
                'ordering': ('-created_at',),
            },
        ),
    ]
