# Generated by Django 5.2.17 on 2026-08-25 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('org', '0003_delete_dynamicfielddefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAppareillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouverte_le', models.DateTimeField(auto_now_add=True, verbose_name='Ouverte le')),
                ('cloturee_le', models.DateTimeField(blank=True, null=True, verbose_name='Clôturée le')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_appareillage', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_appareillage_signees', to=settings.AUTH_USER_MODEL, verbose_name='Signée par')),
            ],
            options={
                'verbose_name': "Session d'appareillage",
                'verbose_name_plural': "Sessions d'appareillage",
                'ordering': ['-ouverte_le'],
            },
        ),
        migrations.CreateModel(
            name='ItemAppareillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('OCCURRENCE', 'Essai ou relevé en attente'), ('RELEVE', 'Relevé technique manquant ou ancien'), ('DERIVE', 'Dérive détectée non résolue'), ('STOCK', 'Pièce de stock sous seuil')], max_length=16)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('verifie_le', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_appareillage_verifies', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.sessionappareillage')),
            ],
            options={
                'verbose_name': "Item de session d'appareillage",
                'verbose_name_plural': "Items de session d'appareillage",
                'ordering': ['categorie', 'libelle'],
            },
        ),
    ]
