# Generated by Django 5.2.9 on 2025-12-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gradechoice_specialitychoice_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MASTER_ADMIN', 'Administrateur général'), ('ADMIN_NAVIRE', 'Administrateur navire'), ('COMMANDANT', 'Commandant'), ('CHEF_SERVICE', 'Chef de service'), ('CHEF_SECTEUR', 'Chef de secteur'), ('CHEF_SECTION', 'Chef de section'), ('EQUIPIER', 'Équipier')], max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
