# Generated by Django 5.2.9 on 2025-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_roleavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFunctionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fonction_service',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='roleavailability',
            name='code',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Administrateur général'), ('ADMIN_NAVIRE', 'Administrateur navire'), ('COMMANDANT', 'Commandant'), ('ETAT_MAJOR', 'État-major'), ('CHEF_SERVICE', 'Chef de service'), ('CHEF_SECTEUR', 'Chef de secteur'), ('CHEF_SECTION', 'Chef de section'), ('EQUIPIER', 'Équipier')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Administrateur général'), ('ADMIN_NAVIRE', 'Administrateur navire'), ('COMMANDANT', 'Commandant'), ('ETAT_MAJOR', 'État-major'), ('CHEF_SERVICE', 'Chef de service'), ('CHEF_SECTEUR', 'Chef de secteur'), ('CHEF_SECTION', 'Chef de section'), ('EQUIPIER', 'Équipier')], max_length=32),
        ),
    ]
