# Generated by Django 5.2.9 on 2025-12-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_servicefunctionchoice_userprofile_fonction_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
