# Generated by Copilot
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notification_time",
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
