# Generated by Django 5.2.17 on 2026-08-25 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_notification_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_time_soir',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
