# Generated by Django 5.2.17 on 2026-08-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_notification_time_soir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleavailability',
            name='code',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Administrateur général'), ('ADMIN_NAVIRE', "Administrateur d'unité"), ('COMMANDANT', 'Commandant'), ('ETAT_MAJOR', 'État-major'), ('CHEF_SERVICE', 'Chef de service'), ('CHEF_SECTEUR', 'Chef de secteur'), ('CHEF_SECTION', 'Chef de section'), ('EQUIPIER', 'Équipier')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Administrateur général'), ('ADMIN_NAVIRE', "Administrateur d'unité"), ('COMMANDANT', 'Commandant'), ('ETAT_MAJOR', 'État-major'), ('CHEF_SERVICE', 'Chef de service'), ('CHEF_SECTEUR', 'Chef de secteur'), ('CHEF_SECTION', 'Chef de section'), ('EQUIPIER', 'Équipier')], max_length=32),
        ),
    ]
