# Generated by Django 5.2.17 on 2026-09-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_roleavailability_code_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionQuartChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fonction de quart',
                'verbose_name_plural': 'Fonctions de quart',
            },
        ),
    ]
