# Generated by Django 5.2.17 on 2026-09-11 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fonctionquartchoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='accounts.specialitychoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites_dont_il_est_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de spécialité',
                'verbose_name_plural': 'Responsables de spécialité',
                'unique_together': {('specialite', 'user')},
            },
        ),
    ]
