# Generated by Django 5.2.17 on 2026-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_responsablespecialite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("clair", "Clair"), ("sombre", "Sombre")],
                default="clair",
                max_length=8,
            ),
        ),
    ]
