# Generated by Django 5.2.7 on 2026-09-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_typeabsence'),
        ('org', '0011_double_equipage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='equipage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='org.equipage', verbose_name='Équipage'),
        ),
    ]
