# Generated by Django 5.2.17 on 2026-10-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_userprofile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="barre_laterale_repliee",
            field=models.BooleanField(default=False),
        ),
    ]
