# Generated by Django 5.2.7 on 2026-09-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profil_equipage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefResponsableSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsables', models.ManyToManyField(blank=True, related_name='chefs', to='accounts.responsablespecialite', verbose_name='Responsables encadrés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadrement_responsables_specialite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef de responsable de spécialité',
                'verbose_name_plural': 'Chefs de responsable de spécialité',
            },
        ),
    ]
