# Generated by Django 5.2.17 on 2026-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_userprofile_barre_laterale_repliee"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="equipage",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Équipage"
            ),
        ),
    ]
