# Generated by Django 5.2.17 on 2026-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_role_commandant_en_second"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fonction_coma",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMAEQ", "COMAEQ (équipage)"),
                    ("COMOPS", "COMOPS (opérations)"),
                    ("COMANAV", "COMANAV (navire)"),
                    ("COMAVIA", "COMAVIA (aviation)"),
                ],
                default="",
                max_length=16,
                verbose_name="Fonction de commandant adjoint",
            ),
        ),
    ]
