# Generated by Django 5.2.17 on 2026-10-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_typeabsence"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mot_de_passe_provisoire",
            field=models.BooleanField(
                default=False,
                help_text="Le marin doit choisir un nouveau mot de passe à sa prochaine connexion.",
                verbose_name="Mot de passe provisoire",
            ),
        ),
    ]
