# Generated by Django 5.2.17 on 2026-08-24 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('starts_at', models.DateTimeField(verbose_name='Date et heure')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_personnels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement personnel',
                'verbose_name_plural': 'Événements personnels',
                'ordering': ['starts_at'],
            },
        ),
    ]
