# Generated by Django 5.2.7 on 2026-09-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalevent',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de fin'),
        ),
    ]
