# Generated by Django 5.2.17 on 2026-09-22 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_typeabsence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(verbose_name='Fin')),
                ('statut', models.CharField(choices=[('DECLAREE', 'Déclarée'), ('VALIDEE', 'Validée')], default='DECLAREE', max_length=16)),
                ('motif', models.TextField(blank=True, default='', verbose_name='Précision (facultatif)')),
                ('validee_le', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('marin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='Marin')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='accounts.typeabsence', verbose_name="Type d'absence")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences et indisponibilités',
                'ordering': ('-date_debut',),
            },
        ),
    ]
