# Generated by Django 5.2.9 on 2025-12-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#0d6efd', max_length=7)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ui_preferences', models.JSONField(blank=True, default=dict)),
                ('status_overrides', models.JSONField(blank=True, default=dict)),
                ('alert_thresholds', models.JSONField(blank=True, default=dict)),
                ('dashboard_widgets', models.JSONField(blank=True, default=dict)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='org.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sector',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='org.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='org.ship'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='org.sector')),
            ],
            options={
                'unique_together': {('sector', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sector',
            unique_together={('service', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('ship', 'name')},
        ),
    ]
