# Generated by Django 5.2.17 on 2026-08-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_dynamicfielddefinition"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DynamicFieldDefinition",
        ),
    ]
