# Generated by Django 5.2.17 on 2026-08-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_delete_dynamicfielddefinition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ship',
            options={'verbose_name': 'Unité', 'verbose_name_plural': 'Unités'},
        ),
        migrations.AddField(
            model_name='ship',
            name='type_unite',
            field=models.CharField(choices=[('NAVIRE', 'Navire'), ('ECOLE', 'École'), ('CENTRE_FORMATION', 'Centre de formation'), ('BUREAU', 'Bureau')], default='NAVIRE', max_length=20, verbose_name="Type d'unité"),
        ),
    ]
