# Generated by Django 5.2.17 on 2026-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_ship_options_ship_type_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='classe_navire',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Classe de navire'),
        ),
    ]
