# Generated by Django 5.2.17 on 2026-09-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_ship_classe_navire'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('ship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_threshold_config', to='org.ship')),
            ],
            options={
                'verbose_name': 'Configuration des seuils de rôle',
                'verbose_name_plural': 'Configurations des seuils de rôle',
            },
        ),
    ]
