# Generated by Django 5.2.17 on 2026-09-11 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_rolethresholdconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableClasseNavire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe_navire', models.CharField(max_length=100, verbose_name='Classe de navire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_navire_dont_il_est_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable de classe de navire',
                'verbose_name_plural': 'Responsables de classe de navire',
                'unique_together': {('classe_navire', 'user')},
            },
        ),
    ]
