# Generated by Django 5.2.17 on 2026-09-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_responsableclassenavire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('active', models.BooleanField(default=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_actives', to='org.ship')),
            ],
            options={
                'verbose_name': 'Activation de module',
                'verbose_name_plural': 'Activations de module',
                'unique_together': {('ship', 'module')},
            },
        ),
    ]
