# Generated by Django 5.2.7 on 2026-09-29 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_moduleactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='capacite_aviation',
            field=models.BooleanField(default=False, verbose_name='Capacité aviation'),
        ),
        migrations.CreateModel(
            name='CommandantAdjoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sigle', models.CharField(choices=[('COMAEQ', 'COMAEQ'), ('COMOPS', 'COMOPS'), ('COMANAV', 'COMANAV'), ('COMAVIA', 'COMAVIA')], max_length=10, verbose_name='Sigle')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandants_adjoints', to='org.ship')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandants_adjoints_titulaire', to=settings.AUTH_USER_MODEL, verbose_name='Titulaire')),
            ],
            options={
                'verbose_name': 'Commandant adjoint',
                'verbose_name_plural': 'Commandants adjoints',
                'ordering': ('ship__name', 'sigle'),
                'unique_together': {('ship', 'sigle')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='commandant_adjoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='org.commandantadjoint', verbose_name='Commandant adjoint'),
        ),
    ]
