# Generated by Django 5.2.17 on 2026-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0008_moduleactivation"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="double_equipage",
            field=models.BooleanField(default=False, verbose_name="Double équipage"),
        ),
        migrations.AddField(
            model_name="ship",
            name="equipage_a_bord",
            field=models.CharField(
                blank=True,
                default="",
                max_length=8,
                verbose_name="Équipage actuellement à bord",
            ),
        ),
    ]
