# Generated by Django 5.2.17 on 2026-10-06 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0009_ship_double_equipage_ship_equipage_a_bord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleveEquipage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("equipage_propose", models.CharField(max_length=8)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=12,
                    ),
                ),
                ("decide_le", models.DateTimeField(blank=True, null=True)),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releves_decidees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "propose_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releves_proposees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releves",
                        to="org.ship",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("statut", "en_attente")),
                        fields=("ship",),
                        name="une_releve_en_attente_par_unite",
                    )
                ],
            },
        ),
    ]
