# Generated by Django 5.2.7 on 2026-09-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_commandants_adjoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandantadjoint',
            options={'ordering': ('ship__name', 'sigle'), 'verbose_name': 'Poste de commandant adjoint (COMA)', 'verbose_name_plural': 'Postes de commandant adjoint (COMA)'},
        ),
        migrations.AlterField(
            model_name='service',
            name='commandant_adjoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='org.commandantadjoint', verbose_name='Poste de commandant adjoint (COMA)'),
        ),
    ]
