# Generated by Django 5.2.7 on 2026-09-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_verbose_name_postes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='date_releve',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la relève'),
        ),
        migrations.AddField(
            model_name='ship',
            name='double_equipage',
            field=models.BooleanField(default=False, verbose_name='Double équipage'),
        ),
        migrations.CreateModel(
            name='Equipage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipages', to='org.ship')),
            ],
            options={
                'verbose_name': 'Équipage',
                'verbose_name_plural': 'Équipages',
                'ordering': ('ship__name', 'nom'),
                'unique_together': {('ship', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='ship',
            name='equipage_a_bord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.equipage', verbose_name='Équipage à bord'),
        ),
        migrations.AddField(
            model_name='ship',
            name='equipage_releve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.equipage', verbose_name='Équipage montant (relève planifiée)'),
        ),
    ]
