# Generated by Django 5.2.7 on 2026-09-29 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_double_equipage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commandantadjoint',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commandantadjoint',
            name='equipage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandants_adjoints', to='org.equipage', verbose_name='Équipage'),
        ),
        migrations.AddField(
            model_name='section',
            name='equipage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='org.equipage', verbose_name='Équipage'),
        ),
        migrations.AddField(
            model_name='sector',
            name='equipage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secteurs', to='org.equipage', verbose_name='Équipage'),
        ),
        migrations.AddField(
            model_name='service',
            name='equipage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='org.equipage', verbose_name='Équipage'),
        ),
        migrations.AddConstraint(
            model_name='commandantadjoint',
            constraint=models.UniqueConstraint(fields=('ship', 'equipage', 'sigle'), name='coma_unique_sigle_par_equipage'),
        ),
        migrations.AddConstraint(
            model_name='commandantadjoint',
            constraint=models.UniqueConstraint(condition=models.Q(('equipage__isnull', True)), fields=('ship', 'sigle'), name='coma_unique_sigle_sans_equipage'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('ship', 'equipage', 'name'), name='service_unique_nom_par_equipage'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('equipage__isnull', True)), fields=('ship', 'name'), name='service_unique_nom_sans_equipage'),
        ),
    ]
