# Generated by Django 5.2.17 on 2026-09-29 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_organisation_par_equipage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynthesePassation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_releve', models.DateField(verbose_name='Date de la relève')),
                ('contenu', models.JSONField(blank=True, default=dict, verbose_name='Contenu figé')),
                ('equipage_descendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.equipage', verbose_name='Équipage descendant')),
                ('equipage_montant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntheses_recues', to='org.equipage', verbose_name='Équipage montant')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntheses_passation', to='org.ship')),
            ],
            options={
                'verbose_name': 'Synthèse de passation',
                'verbose_name_plural': 'Synthèses de passation',
                'ordering': ('-date_releve', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('ship', 'equipage_montant', 'date_releve'), name='passation_unique_par_releve')],
            },
        ),
    ]
