# Generated by Django 5.2.7 on 2026-09-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_synthese_passation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandantEnSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(choices=[('COMMANDANT_EN_SECOND', 'Commandant en second'), ('OFFICIER_EN_SECOND', 'Officier en second')], default='COMMANDANT_EN_SECOND', max_length=30, verbose_name='Libellé du poste')),
                ('equipage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandants_en_second', to='org.equipage', verbose_name='Équipage')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandants_en_second', to='org.ship')),
                ('titulaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes_en_second', to=settings.AUTH_USER_MODEL, verbose_name='Titulaire')),
            ],
            options={
                'verbose_name': 'Poste de commandant en second',
                'verbose_name_plural': 'Postes de commandant en second',
                'constraints': [models.UniqueConstraint(fields=('ship', 'equipage'), name='en_second_unique_par_equipage'), models.UniqueConstraint(condition=models.Q(('equipage__isnull', True)), fields=('ship',), name='en_second_unique_sans_equipage')],
            },
        ),
    ]
