# Generated by Django 5.2.7 on 2026-09-30 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_chefs_responsables_et_en_second'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolethresholdconfig',
            name='droits_en_second',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SuppleanceCommandant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debut', models.DateTimeField(verbose_name='Début de la suppléance')),
                ('fin', models.DateTimeField(verbose_name='Fin de la suppléance')),
                ('motif', models.CharField(blank=True, default='', max_length=200, verbose_name='Motif')),
                ('annulee_le', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('debut_trace', models.BooleanField(default=False)),
                ('fin_tracee', models.BooleanField(default=False)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppleances_annulees', to=settings.AUTH_USER_MODEL)),
                ('designe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppleances_designees', to=settings.AUTH_USER_MODEL)),
                ('equipage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppleances_commandant', to='org.equipage', verbose_name='Équipage')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppleances_commandant', to='org.ship')),
                ('suppleant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppleances_commandant', to=settings.AUTH_USER_MODEL, verbose_name='Suppléant')),
            ],
            options={
                'verbose_name': 'Suppléance du commandant',
                'verbose_name_plural': 'Suppléances du commandant',
                'ordering': ('-debut',),
            },
        ),
    ]
