# Generated by Django 5.2.17 on 2026-08-15 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0021_installationmaintenance_derniere_echeance_heures_and_more"),
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceoccurrence",
            name="installation_maintenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="assets.installationmaintenance",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceoccurrence",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="assets.asset",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceoccurrence",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="maintenance.maintenanceplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("plan__isnull", False),
                        ("asset__isnull", False),
                        ("installation_maintenance__isnull", True),
                    ),
                    models.Q(
                        ("plan__isnull", True),
                        ("asset__isnull", True),
                        ("installation_maintenance__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="occurrence_liee_a_asset_xor_installation",
            ),
        ),
    ]
