# Generated by Django 5.2.17 on 2026-10-07 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_maintenanceexecution_date_validation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceexecution",
            name="intervenants",
            field=models.ManyToManyField(
                blank=True,
                related_name="executions_intervenant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Intervenants",
            ),
        ),
    ]
