# Generated by Django 5.2.17 on 2026-10-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0036_fiches_version_1"),
        ("maintenance", "0004_maintenanceexecution_intervenants"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceexecution",
            name="version_fiche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="assets.checklisttemplate",
                verbose_name="Version de la fiche",
            ),
        ),
    ]
