# Generated by Django 5.2.17 on 2026-10-08 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0037_fiches_flotte"),
        ("maintenance", "0006_executions_version_fiche_existantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceplan",
            name="fiche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="assets.installationmaintenance",
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceplan",
            name="scope",
            field=models.CharField(
                choices=[
                    ("ASSET_TYPE", "Par type d'actif"),
                    ("ASSET", "Par actif"),
                    ("FICHE", "Par fiche flotte"),
                ],
                max_length=16,
            ),
        ),
    ]
