# Generated by Django 5.2.17 on 2026-10-08 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0040_compte_rendu_historique"),
        ("logistics", "0011_ticket_installation"),
        ("maintenance", "0007_fiches_flotte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceexecution",
            name="saisie_origine",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CompteRenduCorrectif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jeton",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duree_estimee_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée estimée (min)"
                    ),
                ),
                ("constat", models.TextField(blank=True, default="")),
                ("diagnostic", models.TextField(blank=True, default="")),
                ("action_realisee", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "conformity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("NON_CONFORME", "Non conforme"),
                            ("A_SURVEILLER", "À surveiller"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("measurements", models.JSONField(blank=True, default=dict)),
                ("pieces", models.JSONField(blank=True, default=list)),
                ("saisie_origine", models.JSONField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervenants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comptes_rendus_correctifs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Intervenants",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compte_rendu",
                        to="logistics.correctiveticket",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version_fiche",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptes_rendus_correctifs",
                        to="assets.checklisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="ModificationCompteRendu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("motif", models.TextField()),
                ("modifications", models.JSONField(default=dict)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correctif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="maintenance.compterenducorrectif",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifications",
                        to="maintenance.maintenanceexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("correctif__isnull", True),
                                ("execution__isnull", False),
                            ),
                            models.Q(
                                ("correctif__isnull", False),
                                ("execution__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="modification_cr_une_seule_cible",
                    )
                ],
            },
        ),
    ]
