# Generated by Django 5.2.17 on 2026-10-05 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brouillon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cle",
                    models.CharField(max_length=120, verbose_name="clé du formulaire"),
                ),
                (
                    "contenu",
                    models.JSONField(default=dict, verbose_name="contenu des champs"),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="libellé"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="adresse de reprise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brouillons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "brouillon",
                "verbose_name_plural": "brouillons",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "cle"),
                        name="brouillon_unique_par_utilisateur_et_cle",
                    )
                ],
            },
        ),
    ]
