# Generated by Django 5.2.17 on 2026-09-21 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0028_migrer_zones_vers_positions'),
        ('logistics', '0011_ticket_installation'),
        ('org', '0007_responsableclassenavire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ronde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_modele', models.PositiveIntegerField(default=1)),
                ('nom', models.CharField(max_length=150)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('EN_RETARD', 'En retard')], default='A_FAIRE', max_length=10)),
                ('debut', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes_assignees', to=settings.AUTH_USER_MODEL)),
                ('realisee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes_realisees', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes', to='org.sector')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes', to='org.service')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes', to='org.ship')),
            ],
            options={
                'verbose_name': 'Ronde',
                'ordering': ['-date_prevue', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ResultatPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('libelle', models.CharField(max_length=200)),
                ('consigne', models.CharField(blank=True, default='', max_length=255)),
                ('equipement_libelle', models.CharField(blank=True, default='', max_length=255)),
                ('avec_mesure', models.BooleanField(default=False)),
                ('unite_mesure', models.CharField(blank=True, default='', max_length=20)),
                ('gravite', models.PositiveSmallIntegerField(default=3)),
                ('resultat', models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme')], default='', max_length=15)),
                ('mesure', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('saisi_le', models.DateTimeField(blank=True, null=True)),
                ('anomalie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ronde', to='logistics.anomalie')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.asset')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.installation')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ronde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='rondes.ronde')),
            ],
            options={
                'ordering': ['ordre', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RondeModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la ronde')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('periodicite_jours', models.PositiveSmallIntegerField(default=1, help_text='Une ronde est proposée tous les N jours (1 = tous les jours).', verbose_name='Périodicité (en jours)')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ronde_modeles_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Marin désigné')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ronde_modeles', to='org.sector')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ronde_modeles', to='org.service')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ronde_modeles', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de ronde',
                'verbose_name_plural': 'Modèles de ronde',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='ronde',
            name='modele',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondes', to='rondes.rondemodele'),
        ),
        migrations.CreateModel(
            name='PointControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('libelle', models.CharField(max_length=200, verbose_name='Point à contrôler')),
                ('consigne', models.CharField(blank=True, default='', max_length=255, verbose_name='Consigne')),
                ('avec_mesure', models.BooleanField(default=False, verbose_name='Relever une valeur')),
                ('unite_mesure', models.CharField(blank=True, default='', max_length=20, verbose_name='Unité')),
                ('gravite', models.PositiveSmallIntegerField(default=3, verbose_name="Gravité de l'anomalie si non conforme")),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ronde', to='assets.asset')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_ronde', to='assets.installation')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='rondes.rondemodele')),
            ],
            options={
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
