# Generated by Django 5.2.17 on 2026-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_level_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("warning", "Important"),
                    ("danger", "Urgent"),
                ],
                default="info",
                max_length=10,
            ),
        ),
    ]
