# Generated by Django 5.2.17 on 2026-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcourse",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="unlocks", to="training.trainingcourse"
            ),
        ),
    ]
