# Generated by Django 5.2.17 on 2026-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_trainingcourse_prerequisites"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcourse",
            name="category",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
