# Generated by Django 5.2.17 on 2026-08-18 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_trainingcourse_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcourse",
            name="referents",
            field=models.ManyToManyField(
                blank=True,
                related_name="formations_referentes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
