# Generated by Django 5.2.17 on 2026-08-20 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_trainingcourse_referents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="capacite_max",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="reservations",
            field=models.ManyToManyField(
                blank=True,
                related_name="training_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
