# Generated by Django 5.2.17 on 2026-08-24 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_delete_dynamicfielddefinition'),
        ('training', '0005_trainingsession_capacite_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentFormationNavire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referent_formation', to='org.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navires_dont_il_est_referent_formation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
