# Generated by Django 5.2.7 on 2026-08-25 22:22
#
# Migration finale (phase 3/3) de la portabilité des formations (cf. tâche
# Notion « Formation unique et portable entre navires ») : retire
# TrainingCourse.sector/referents. À N'APPLIQUER QU'APRÈS avoir lancé la
# commande de gestion `python manage.py fusionner_formations` (d'abord avec
# --dry-run pour revoir le rapport, puis réellement) — sans quoi le
# rattachement navire et les référents de chaque formation existante seraient
# perdus au lieu d'être convertis en TrainingRequirement/ReferentFormation.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_referentformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='referents',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='sector',
        ),
    ]
