# Generated by Django 5.2.17 on 2026-08-26 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_ship_options_ship_type_unite'),
        ('training', '0008_remove_trainingcourse_referents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nb_places_demandees', models.PositiveIntegerField(verbose_name='Nombre de places demandées')),
                ('nb_places_attribuees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de places attribuées')),
                ('statut', models.CharField(choices=[('REQUESTED', 'Demandée'), ('GRANTED', 'Attribuée'), ('REFUSED', 'Refusée'), ('CANCELLED', 'Annulée')], default='REQUESTED', max_length=16)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_places_attribuees', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_places', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_places', to='training.trainingsession')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_places', to='org.ship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de places',
                'verbose_name_plural': 'Demandes de places',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlaceAffectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_affectees', to='training.demandeplace')),
                ('marin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_affectees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Place affectée',
                'verbose_name_plural': 'Places affectées',
                'unique_together': {('demande_place', 'marin')},
            },
        ),
    ]
