# Generated by Django 5.2.7 on 2026-08-26 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_alter_ship_options_ship_type_unite'),
        ('training', '0009_demandeplace_placeaffectee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatureFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('PENDING_APPROVAL', 'En attente de validation'), ('TRANSMITTED', "Transmise à l'organisme"), ('SELECTED', 'Sélectionnée'), ('REJECTED_HIERARCHIE', 'Refusée par la hiérarchie'), ('REJECTED_BRH', 'Refusée par le BRH'), ('REJECTED_ORGANISME', "Refusée par l'organisme")], default='PENDING_APPROVAL', max_length=24)),
                ('date_validation_hierarchie', models.DateTimeField(blank=True, null=True)),
                ('date_validation_brh', models.DateTimeField(blank=True, null=True)),
                ('brh_validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_validees_brh', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='training.trainingcourse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('hierarchie_validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_validees_hierarchie', to=settings.AUTH_USER_MODEL)),
                ('marin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_formation', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature à une formation',
                'verbose_name_plural': 'Candidatures à une formation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PersonnelBRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels_brh', to='org.ship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navires_brh', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel BRH',
                'verbose_name_plural': 'Personnels BRH',
                'unique_together': {('ship', 'user')},
            },
        ),
    ]
