# Generated by Django 5.2.7 on 2026-08-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_candidatureformation_personnelbrh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='gere_par_le_bord',
            field=models.BooleanField(default=False, verbose_name='Gérée par un bord'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='statut_validation',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WAITING_VALIDATION', 'En attente de validation'), ('REFUSED', 'Refusée')], default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
