# Generated by Django 5.2.17 on 2026-08-27 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_trainingcourse_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liste_attente', to='training.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_liste_attente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée en liste d'attente",
                'verbose_name_plural': "Entrées en liste d'attente",
                'ordering': ('created_at',),
                'unique_together': {('session', 'user')},
            },
        ),
    ]
