# Generated by Django 5.2.17 on 2026-08-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_trainingwaitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='bareme',
            field=models.FileField(blank=True, null=True, upload_to='training_baremes/', verbose_name='Barème'),
        ),
    ]
