# Generated by Django 5.2.17 on 2026-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0013_trainingcourse_bareme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingrequirement",
            name="applies_to_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COMMANDANT", "Commandant"),
                    ("COMMANDANT_EN_SECOND", "Commandant en second"),
                    ("ETAT_MAJOR", "État-major"),
                    ("CHEF_SERVICE", "Chef de service"),
                    ("CHEF_SECTEUR", "Chef de secteur"),
                    ("CHEF_SECTION", "Chef de section"),
                    ("EQUIPIER", "Équipier"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
