# Generated by Django 5.2.17 on 2026-09-23 22:17

import matrix.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_trainingcourse_bareme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='bareme',
            field=models.FileField(blank=True, null=True, upload_to='training_baremes/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'odt', 'ods', 'txt', 'csv'), 20971520, verifier_image=True)], verbose_name='Barème'),
        ),
        migrations.AlterField(
            model_name='trainingrecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='training_certificates/', validators=[matrix.core.validators.ValidateurFichierTeleverse(('jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'odt', 'ods', 'txt', 'csv'), 20971520, verifier_image=True)]),
        ),
    ]
